services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - HTTP_PROXY=http://172.17.0.1:7890
        - HTTPS_PROXY=http://172.17.0.1:7890
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend-dev
      args:
        - HTTP_PROXY=http://172.17.0.1:7890
        - HTTPS_PROXY=http://172.17.0.1:7890
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - HTTP_PROXY=http://172.17.0.1:7890
        - HTTPS_PROXY=http://172.17.0.1:7890
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dexer
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dexerblog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dexer -d dexerblog" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
