services:
  dexerblog:
    build:
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit features
      target: runner
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Backend API
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_PORT=3001
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: dexerblog-app

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - dexerun
  #   restart: unless-stopped
